---
apiVersion: argoproj.io/v1alpha1
kind: ConfigManagementPlugin
metadata:
  name: argocd-secure-app-plugin
spec:
  version: v0.10.3
  generate:
    command: ["argocd-secure-app-plugin"]
  discover:
    fileName: "*"
